language: julia

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      email: false
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip
